export const tagTypes = {
  auth: "Auth",
  user: "User",
  banner: "Banner",
  dashboard: "Dashboard",
  owner: "Owner",
  listing: "Listing",
  advertisement: "Advertisement",
  payment: "Payment",
  review: "Review",
  booking: "Booking",
  reportsAnalytics: "ReportsAnalytics",
  adminTeam: "AdminTeam",
  legalDocuments: "LegalDocuments",
  settings: "Settings",
  category: "Category",
  product: "Product",
  order: "Order",
  customer: "Customer",
  finance: "Finance",
  staff: "Staff",
  role: "Role",
  permission: "Permission",
};

export const tagTypesList = [
  tagTypes.auth,
  tagTypes.user,
  tagTypes.banner,
  tagTypes.dashboard,
  tagTypes.owner,
  tagTypes.listing,
  tagTypes.advertisement,
  tagTypes.payment,
  tagTypes.review,
  tagTypes.booking,
  tagTypes.reportsAnalytics,
  tagTypes.adminTeam,
  tagTypes.legalDocuments,
  tagTypes.settings,
  tagTypes.category,
  tagTypes.product,
  tagTypes.order,
  tagTypes.customer,
  tagTypes.finance,
  tagTypes.staff,
  tagTypes.role,
  tagTypes.permission,
];
